### PR TITLE
mentor profile page ui

### LINKED ISSUE #27: UI for Profile page for Mentor
Show the following details:
1)Name
2)Github Id
3)Projects
4)Email
5)Phone
6)College

Refer to the participant profile page.

### PR DESCRIPTION
**Pull request by shmiitg**
Fixes #27 
Desktop View
Screenshot (319)
Mobile View
Screenshot (320)

### CODE REVIEW

**Comment by KartuzGupta** [comment]
Just change the font-style and add a projects icon. Rest everything is fine.

**Comment by shmiitg** [comment]
image
Done

**Comment by KartuzGupta** [comment]
Highlight "Personal Details" and add a "Projects" option in the side menu.

**Comment by shmiitg** [comment]
> Highlight "Personal Details" and add a "Projects" option in the side menu.

ok

**Comment by shmiitg** [comment]
Done

**Comment by shmiitg** [comment]
Screenshot (339)

**Comment by KartuzGupta** [comment]
Merged and will award you points

**Pull request merged**
