### PR TITLE
CA signup page changes

### PR DESCRIPTION
**Pull request by padmaja2305**
changes made in the sign up page of CA 
image
image
image

### CODE REVIEW

**Comment by KartuzGupta** [comment]
> changes made in the sign up page of CA image image image

Nice Work but found an issue, please rectify it!!
CODEPEAK - Google Chrome 15-12-2021 13_27_54

(A lot of space under the form)

**Comment by padmaja2305** [comment]
ok working on it

**Comment by padmaja2305** [comment]
Done the required changes
Please check

**Comment by KartuzGupta** [comment]
> Done the required changes Please check

Reviewed the changes!! Nice work. Merging your PR and awarding you points.

**Pull request merged**
