### PR TITLE
created paricipant profile UI

### PR DESCRIPTION
**Pull request by aritroCoder**
Solves issue #6

### CODE REVIEW

**Comment by KartuzGupta** [comment]
> Solves issue #6

CODEPEAK - Google Chrome 01-01-2022 15_03_57

Make that profile icon and name better. Not looking good in Mobile view.

**Comment by aritroCoder** [comment]
I have noticed a peculiar behaviour here with the CSS that even if it is not imported, the CSS effects are getting applied to other pages also

**Comment by shmiitg** [comment]
> I have noticed a peculiar behaviour here with the CSS that even if it is not imported, the CSS effects are getting applied to other pages also, so to add new CSS we have to give unique class names to every element

use css modules, that will give unique names to every class and will not be transferred to other pages

**Comment by aritroCoder** [comment]
image

image

Please check the updated changes now

**Comment by KartuzGupta** [comment]
CODEPEAK - Google Chrome 05-01-2022 10_02_56

The input lines are too small. Please rectify this issue.

**Comment by aritroCoder** [comment]
@KartuzGupta  I have made the input lines longer, if you want me to elongate them more I can do that but I think that will not look cool

**Comment by KartuzGupta** [comment]
> @KartuzGupta I have made the input lines longer, if you want me to elongate them more I can do that but I think that will not look cool

can you send an image

**Comment by aritroCoder** [comment]
image
image

**Comment by KartuzGupta** [comment]
> image image

Okay merging it and awarding you points

**Comment by aritroCoder** [comment]
It was a intermediate issue right? It should have 10 points then but I got 5 point

**Pull request merged**
