### PR TITLE
Leaderboard design

### LINKED ISSUE #13: Better UI for Leaderboard Page
The [Leaderboard Page](https://www.codepeak.tech/leaderboard) does not look up to the mark.
Would love to see your designs for this page.

Points will depend upon your design.

### PR DESCRIPTION
**Pull request by nguyenhung15913**
Fixes #13 
This is the first design for the leaderboard page. Feel free to ask me for any correction, thanks

### CODE REVIEW

**Comment by KartuzGupta** [comment]
> Fixes #13 This is the first design for the leaderboard page. Feel free to ask me for any correction, thanks

I appreciate the hard work you have put in but i am sorry to say that the design is not up to the mark. There a few issue which I would like to point out:
1) The choice of colours is not good.
CODEPEAK - Google Chrome 11-12-2021 14_01_27

2) If more than 5 rows are displayed then the rows except the top 5 are transparent.
CODEPEAK - Google Chrome 11-12-2021 14_01_35

3)The First and Previous buttons are initially translucent which hampers the UI.
CODEPEAK - Google Chrome 11-12-2021 14_01_27 (2)

Please work on these sections and make a PR. If you face any issue (even if you think its very silly) ,just ask us on our discord server . Don't hesitate. We are all learners here.

[Discord Server Link](https://discord.gg/xhQ9N9Z3jc) - https://discord.gg/xhQ9N9Z3jc

**Comment by KartuzGupta** [comment]
Any Updates

**Comment by nguyenhung15913** [comment]
> Any Updates

Hi I am still working on it

**Comment by VishalIITP** [comment]
> > Any Updates
> 
> Hi I am still working on it
Hey! @nguyenhung15913 what's the progress

**Comment by VishalIITP** [comment]
We got good design suggestions !! 
Closing the issue as of now

**Pull request closed without merging**
